"""Generate Supabase seed SQL for student_guardians (PENJAGA 1/2) from the
school's XEA4402 student master export. Read-only against the source file;
writes SQL under supabase/seed/. Does not connect to any database.

Each student row can have up to two guardian blocks (PENJAGA 1/2); a block
is skipped if its name column is blank. Matches to students by student_id
(ID MURID) via a subquery, so a student not yet in the DB simply yields no
insert rather than an error. Safe to re-run: on conflict (student_id,
full_name) do update.

Run: python scripts/generate_guardian_seed_sql.py
"""

from __future__ import annotations

from pathlib import Path

import openpyxl

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = Path(r"D:\Summit\System\docs")
SEED_DIR = REPO_ROOT / "supabase" / "seed"
SEED_DIR.mkdir(parents=True, exist_ok=True)

STUDENT_MASTER_FILE = DOCS_DIR / "XEA4402 Keseluruhan Murid as of 2026-07-19.xlsx"
OUTPUT_FILE = SEED_DIR / "guardians_seed.sql"


def sql_str(value) -> str:
    if value is None:
        return "NULL"
    text = str(value).strip()
    if not text:
        return "NULL"
    return "'" + text.replace("'", "''") + "'"


def sql_int(value) -> str:
    if value is None:
        return "NULL"
    return str(int(value))


def load_guardians():
    wb = openpyxl.load_workbook(STUDENT_MASTER_FILE, data_only=True, read_only=True)
    ws = wb["Worksheet"]

    guardians: list[dict] = []

    for row in ws.iter_rows(min_row=7, values_only=True):
        student_id = row[1]
        if student_id is None:
            continue
        student_id = int(student_id)

        # PENJAGA 1: name idx33, IC idx34, relationship idx36,
        # office phone idx41, mobile phone idx42.
        if row[33]:
            guardians.append(
                {
                    "student_id": student_id,
                    "full_name": row[33],
                    "ic_number": row[34],
                    "relationship": row[36],
                    "phone": row[42] or row[41],
                    "is_primary": True,
                }
            )

        # PENJAGA 2: name idx44, IC idx45, relationship idx47,
        # office phone idx52, mobile phone idx53.
        if row[44]:
            guardians.append(
                {
                    "student_id": student_id,
                    "full_name": row[44],
                    "ic_number": row[45],
                    "relationship": row[47],
                    "phone": row[53] or row[52],
                    "is_primary": False,
                }
            )

    wb.close()
    return guardians


def write_sql(guardians: list[dict]):
    with OUTPUT_FILE.open("w", encoding="utf-8") as f:
        f.write("-- Generated by scripts/generate_guardian_seed_sql.py -- do not hand-edit.\n")
        f.write(f"-- {len(guardians)} guardian rows from XEA4402 PENJAGA 1/2 blocks.\n\n")
        for g in guardians:
            f.write(
                "insert into public.student_guardians "
                "(student_id, full_name, relationship, ic_number, phone, is_primary) "
                "select s.id, "
                f"{sql_str(g['full_name'])}, {sql_str(g['relationship'])}, "
                f"{sql_str(g['ic_number'])}, {sql_str(g['phone'])}, {'true' if g['is_primary'] else 'false'} "
                f"from public.students s where s.student_id = {sql_int(g['student_id'])} "
                "on conflict (student_id, full_name) do update set "
                "relationship = excluded.relationship, ic_number = excluded.ic_number, "
                "phone = excluded.phone, is_primary = excluded.is_primary;\n"
            )


def main():
    guardians = load_guardians()
    write_sql(guardians)
    primary = sum(1 for g in guardians if g["is_primary"])
    print(f"Wrote {len(guardians)} guardian rows ({primary} primary, {len(guardians) - primary} secondary) to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
